name: Zanata
markdown: kramdown
highlighter: rouge
url: http://localhost:4000
permalink: /:title
show_drafts: false

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
